// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljkvsudqbcievkoxwgbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxqa3ZzdWRxYmNpZXZrb3h3Z2JvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NTM1ODIsImV4cCI6MjA2OTQyOTU4Mn0.e5hM9rM7HKIfkIjlOD0AGDOi5USHbLqkvxOmnQ0KBKY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});